export const category = [
    {"id": 1, "category": "Shoes", "checked": false},
    {"id": 2, "category": "Men T-shirts", "checked": false},
    {"id": 3, "category": "Makeup", "checked": false},
    {"id": 4, "category": "Jewellery", "checked": false},
    {"id": 5, "category": "Women T-shirts", "checked": false},
    {"id": 6, "category": "Furniture", "checked": false},
    {"id": 7, "category": "Electronics", "checked": false},
    {"id": 8, "category": "Books", "checked": false},
    {"id": 9, "category": "Sportswear", "checked": false},
    {"id": 10, "category": "Home Decor", "checked": false},
    {"id": 11, "category": "Kitchen Appliances", "checked": false},
    {"id": 12, "category": "Toys", "checked": false},
    {"id": 13, "category": "Fitness Equipment", "checked": false},
    {"id": 14, "category": "Pet Supplies", "checked": false},
    {"id": 15, "category": "Garden Tools", "checked": false},
    {"id": 16, "category": "Office Supplies", "checked": false},
    {"id": 17, "category": "Art Supplies", "checked": false},
    {"id": 18, "category": "Craft Supplies", "checked": false},
    {"id": 19, "category": "Baby Clothing", "checked": false},
    {"id": 20, "category": "Maternity Wear", "checked": false},
    {"id": 21, "category": "Swimwear", "checked": false},
    {"id": 22, "category": "Luggage", "checked": false},
    {"id": 23, "category": "Travel Accessories", "checked": false},
    {"id": 24, "category": "Outdoor Gear", "checked": false},
    {"id": 25, "category": "Camping Equipment", "checked": false},
    {"id": 26, "category": "Health & Beauty", "checked": false},
    {"id": 27, "category": "Perfumes", "checked": false},
    {"id": 28, "category": "Watches", "checked": false},
    {"id": 29, "category": "Sunglasses", "checked": false},
    {"id": 30, "category": "Handbags", "checked": false},
    {"id": 31, "category": "Wallets", "checked": false},
    {"id": 32, "category": "Bath & Body", "checked": false},
    {"id": 33, "category": "Skincare", "checked": false},
    {"id": 34, "category": "Hair Care", "checked": false},
    {"id": 35, "category": "Personal Care", "checked": false},
    {"id": 36, "category": "Stationery", "checked": false},
    {"id": 37, "category": "Educational Toys", "checked": false},
    {"id": 38, "category": "Board Games", "checked": false},
    {"id": 39, "category": "Puzzles", "checked": false},
    {"id": 40, "category": "Musical Instruments", "checked": false},
    {"id": 41, "category": "Art Books", "checked": false},
    {"id": 42, "category": "Cookbooks", "checked": false},
    {"id": 43, "category": "Fiction Books", "checked": false},
    {"id": 44, "category": "Non-Fiction Books", "checked": false},
    {"id": 45, "category": "Romance Novels", "checked": false},
    {"id": 46, "category": "Action Figures", "checked": false},
    {"id": 47, "category": "Building Blocks", "checked": false},
    {"id": 48, "category": "Dolls", "checked": false},
    {"id": 49, "category": "Stuffed Animals", "checked": false},
    {"id": 50, "category": "Remote Control Toys", "checked": false},
    {"id": 51, "category": "Cardio Equipment", "checked": false},
    {"id": 52, "category": "Strength Training", "checked": false},
    {"id": 53, "category": "Yoga & Pilates", "checked": false},
    {"id": 54, "category": "Team Sports", "checked": false},
    {"id": 55, "category": "Water Sports", "checked": false},
    {"id": 56, "category": "Hiking Gear", "checked": false},
    {"id": 57, "category": "Cycling Gear", "checked": false},
    {"id": 58, "category": "Tent & Sleeping Bags", "checked": false},
    {"id": 59, "category": "Cooking Appliances", "checked": false},
    {"id": 60, "category": "Dining Furniture", "checked": false},
    {"id": 61, "category": "Bedroom Furniture", "checked": false},
    {"id": 62, "category": "Living Room Furniture", "checked": false},
    {"id": 63, "category": "Outdoor Furniture", "checked": false},
    {"id": 64, "category": "Office Furniture", "checked": false},
    {"id": 65, "category": "Gaming Furniture", "checked": false},
    {"id": 66, "category": "Rugs & Carpets", "checked": false},
    {"id": 67, "category": "Lighting", "checked": false},
    {"id": 68, "category": "Wall Decor", "checked": false},
    {"id": 69, "category": "Mirrors", "checked": false},
    {"id": 70, "category": "Planters & Pots", "checked": false},
    {"id": 71, "category": "Gardening Tools", "checked": false},
    {"id": 72, "category": "Patio Furniture", "checked": false},
    {"id": 73, "category": "Office Supplies", "checked": false},
    {"id": 74, "category": "Desk Accessories", "checked": false},
    {"id": 75, "category": "Notebooks", "checked": false},
    {"id": 76, "category": "Pens & Pencils", "checked": false},
    {"id": 77, "category": "Planners", "checked": false},
    {"id": 78, "category": "Painting Supplies", "checked": false},
    {"id": 79, "category": "Drawing Supplies", "checked": false},
    {"id": 80, "category": "Craft Kits", "checked": false},
    {"id": 81, "category": "Baby Gear", "checked": false},
    {"id": 82, "category": "Diapering", "checked": false},
    {"id": 83, "category": "Feeding", "checked": false},
    {"id": 84, "category": "Baby Safety", "checked": false},
    {"id": 85, "category": "Baby Toys", "checked": false},
    {"id": 86, "category": "Maternity Clothing", "checked": false},
    {"id": 87, "category": "Nursery Furniture", "checked": false},
    {"id": 88, "category": "Nursery Decor", "checked": false},
    {"id": 89, "category": "Baby Bath", "checked": false},
    {"id": 90, "category": "Baby Health", "checked": false},
    {"id": 91, "category": "Swimwear", "checked": false},
    {"id": 92, "category": "Ski & Snowboard Gear", "checked": false},
    {"id": 93, "category": "Climbing Gear", "checked": false},
    {"id": 94, "category": "Surfing Gear", "checked": false},
    {"id": 95, "category": "Camping Gear", "checked": false},
    {"id": 96, "category": "Outdoor Clothing", "checked": false},
    {"id": 97, "category": "Cycling Clothing", "checked": false},
    {"id": 98, "category": "Running Shoes", "checked": false},
    {"id": 99, "category": "Sports Nutrition", "checked": false},
    {"id": 100, "category": "Water Bottles", "checked": false}
  ]  